name: Build Chess Detector APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Grant execute permission for Gradle wrapper
        working-directory: ChessDetector
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: ChessDetector
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: chess-detector-debug-apk
          path: ChessDetector/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          
      - name: Display Build Info
        run: |
          echo "✅ Chess Detector APK built successfully!"
          ls -lh ChessDetector/app/build/outputs/apk/debug/app-debug.apk
